version: '3.8'

services:
  app:
    container_name: my_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - my_mongo
    env_file:
      - ./.env
  my_mongo:
    container_name: my_mongo
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PWD}
    ports:
      - "27017:27017"